module:
  noProxy: none
  noVendor: ""
  private: '*.*'
  proxy: direct
  replacements: ""
  workspace: "off"
  hugoVersion:
    extended: false

csp:
  keys: ['none', 'self', 'strict-dynamic', 'report-sample', 'unsafe-inline', 'unsafe-hashes']
  experimental:
    allow: false
    keys: []
  report-only: false
