module:
  noProxy: none
  noVendor:
  private: '*.*'
  proxy: direct
  workspace: "off"
  hugoVersion:
    extended: false

mediaTypes:
  text/netlify:
    suffixes: [""]
    delimiter: ""

outputFormats:
  HEADER:
    mediaType: "text/netlify"
    basename: "_headers"
    isPlainText: true
    notAlternative: true

Params:
  xHeadersConfig:
    keysSrc: ["Content-Type-Options", "Frame-Options", "XSS-Protection"]
    foValues: ["deny", "sameorigin"]
    values: [true, false]
    ctpDefault: "nosniff"
    xssDefault: "1; mode=block"
  cspConfig:
    keysSrc: ["default", "script", "style", "object", "connect", "font", "frame", "img", "manifest", "media", "worker"]
    keysUri: [base, report]
    values: ['none', 'self', 'strict-dynamic', 'report-sample', 'unsafe-inline', 'unsafe-hashes']
    experimental:
      allow: false
      keys: []
    reportOnly: false
