module:
  noProxy: none
  noVendor: ""
  private: '*.*'
  proxy: direct
  replacements: ""
  workspace: "off"
  hugoVersion:
    extended: false

csp:
  keys: ['none', 'self', 'strict-dynamic', 'report-sample', 'unsafe-inline', 'unsafe-hashes']
  experimental:
    allow: false
    keys: []
  report-only: false

  ## default-src 'self';
  ##   script-src 'report-sample' 'self' https://piano-brilliant.desider.at/script.js;
  ##   style-src 'report-sample' 'self';
  ##   object-src 'none';
  ##   base-uri 'self';
  ##   connect-src 'self';
  ##   font-src 'self';
  ##   frame-src 'self';
  ##   img-src 'self' data: https://piano-brilliant.desider.at;
  ##   manifest-src 'self';
  ##   media-src 'self';
  ##   report-uri https://643aea21f1e3671a291368de.endpoint.csper.io/?v=0;
  ##   worker-src 'none';
